### ISSUE TITLE
User Journey 1 - tourist

### ISSUE THREAD

**Issue by ab-stha** [SchoolOfCode/final-project-internet-explorers#15]
```[tasklist]
### Tasks
- [ ] Landing page (homepage) must show a navigational map
- [ ] The map must show any available shops that use Baggit
- [ ] There must be a searchbar to search for shops near or in a specific location
- [ ] When a shop indicated by a marker is clicked, a pop up should trigger
```
