### ISSUE TITLE
Ideation and planning

### ISSUE THREAD

**Issue by ab-stha** [SchoolOfCode/final-project-internet-explorers#16]
```[tasklist]
### Tasks
- [ ] Think of a problem statement - 'the lack of a convenient and organized space for travelers to store and manage their belongings'
- [ ] Possible solution to that problem - 'an app that provides business opportunity for shopkeepers as well as a way for tourists to leave their luggage in storage for a while at convenient locations'
- [ ] Name of app - 'Baggit'
```
