### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by ab-stha** [SchoolOfCode/final-project-internet-explorers#17]
```[tasklist]
### Tasks
- [ ] Set up a yml file to automate some tests
- [ ] yml file should contain lint, format tests
- [ ] Upon a new pull request from a feature branch to main branch, these tests should run automatically
- [ ] Vercel runs some deployment checks too
```
